/**
 * Hand-maintained row types for the tables this app reads/writes.
 *
 * These mirror supabase/migrations. After connecting a real database you can
 * regenerate a fully-typed client with:
 *   supabase gen types typescript --local > src/lib/db/database.types.ts
 * and swap the untyped clients for `createClient<Database>()`. Until then these
 * interfaces are the type boundary for query results.
 */

import type { Role } from '@/lib/domain/rbac';
import type { ConditionCode } from '@/lib/domain/products';
import type { MovementType } from '@/lib/domain/stock-ledger';
import type { AttendanceStatus, Shift } from '@/lib/domain/attendance';
import type { Currency, PoStatus } from '@/lib/domain/purchasing';
import type { SoStatus } from '@/lib/domain/sales';
import type { PayrollStatus, DeductionKind } from '@/lib/domain/payroll';

export interface ProfileRow {
  id: string;
  email: string;
  full_name: string | null;
  role: Role;
  is_active: boolean;
  created_at: string;
}

export interface LocationRow {
  id: string;
  code: string;
  name: string;
  is_active: boolean;
  created_at: string;
}

export interface ProductFamilyRow {
  id: string;
  code: string;
  name: string; // Chinese product-family name (required)
  name_english: string | null;
  default_unit: string;
  description: string | null;
  is_active: boolean;
  created_at: string;
}

export interface SkuRow {
  id: string;
  family_id: string;
  diameter: string | null;
  size: string | null;
  hole: string | null;
  rod_count: string | null;
  extra: string | null;
  condition: ConditionCode;
  unit: string;
  minimum_level: number;
  is_active: boolean;
  notes: string | null;
  created_at: string;
}

export interface StockMovementRow {
  id: string;
  sku_id: string;
  location_id: string;
  type: MovementType;
  quantity: number; // signed
  business_date: string; // YYYY-MM-DD
  transfer_group_id: string | null;
  override_reason: string | null;
  notes: string | null;
  attachment_path: string | null;
  purchase_order_item_id: string | null;
  batch_reference: string | null;
  created_by: string | null;
  created_at: string;
}

export interface AttendanceGroupRow {
  id: string;
  name: string;
  sort_order: number;
  is_active: boolean;
  created_at: string;
}

/** Non-sensitive employee columns (public.employees). */
export interface EmployeeRow {
  id: string;
  employee_code: string; // ZY-0001, generated by the DB
  seq_no: number; // permanent, never-reused sequence number
  name_khmer: string | null;
  name_english: string | null;
  name_chinese: string | null;
  phone: string | null;
  department: string | null;
  position: string | null;
  start_date: string | null;
  is_active: boolean;
  pay_type: 'daily';
  photo_path: string | null;
  notes: string | null;
  // Attendance-group profile fields (used by the grouped report).
  attendance_group_id: string | null;
  display_name: string | null;
  job_title: string | null;
  label: string | null;
  created_at: string;
}

/**
 * Sensitive employee payroll data (public.employee_private). RLS restricts reads
 * to Owner / System Admin / Payroll Admin.
 */
export interface EmployeePrivateRow {
  employee_id: string;
  base_salary: number | null;
  daily_rate: number | null;
  emergency_contact: string | null;
  updated_at: string;
}

export interface AttendanceRow {
  id: string;
  employee_id: string;
  business_date: string;
  shift: Shift;
  status: Exclude<AttendanceStatus, 'unmarked'>;
  notes: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface AuditLogRow {
  id: string;
  actor_id: string | null;
  actor_email: string | null;
  action: string;
  entity: string;
  entity_id: string | null;
  old_value: unknown;
  new_value: unknown;
  created_at: string;
}

export interface SentReportRow {
  id: string;
  report_key: string; // idempotency key, e.g. attendance:morning:2026-07-24
  report_type: string;
  business_date: string;
  chat_id: string | null;
  destination_group: 'attendance' | 'inventory' | null;
  status: 'sent' | 'failed';
  detail: string | null;
  created_at: string;
}

export interface TelegramSettingsRow {
  id: number;
  morning_enabled: boolean;
  afternoon_enabled: boolean;
  inventory_enabled: boolean;
  morning_time: string; // HH:mm (Asia/Phnom_Penh) — attendance morning
  afternoon_time: string; // HH:mm (Asia/Phnom_Penh) — attendance afternoon
  inventory_time: string; // HH:mm (Asia/Phnom_Penh) — daily inventory
  report_language: 'en' | 'zh'; // future-ready; reports currently always Chinese
  // --- Attendance Group destination (morning + afternoon reports) -----------
  attendance_chat_id: string | null;
  attendance_group_enabled: boolean;
  attendance_last_status: 'sent' | 'failed' | null;
  attendance_last_error: string | null;
  attendance_last_sent_at: string | null;
  // --- Inventory Group destination (daily inventory report) -----------------
  inventory_chat_id: string | null;
  inventory_group_enabled: boolean;
  inventory_last_status: 'sent' | 'failed' | null;
  inventory_last_error: string | null;
  inventory_last_sent_at: string | null;
  updated_at: string;
}

// --- Purchasing (Second pass) ------------------------------------------------

export interface SupplierRow {
  id: string;
  name: string;
  name_chinese: string | null;
  name_english: string | null;
  contact_person: string | null;
  phone: string | null;
  address: string | null;
  tax_id: string | null;
  payment_terms: string | null;
  default_currency: Currency;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface PurchaseOrderRow {
  id: string;
  po_number: string | null;
  supplier_id: string;
  order_date: string;
  expected_arrival_date: string | null;
  currency: Currency;
  status: PoStatus;
  notes: string | null;
  attachment_path: string | null;
  created_by: string | null;
  issued_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface PurchaseOrderItemRow {
  id: string;
  purchase_order_id: string;
  sku_id: string;
  location_id: string;
  unit: string;
  ordered_qty: number;
  unit_cost: number;
  line_total: number;
  created_at: string;
}

export interface PurchaseOrderItemReceivedRow {
  item_id: string;
  received_qty: number;
}

// --- Sales (Third pass) -------------------------------------------------------

export interface CustomerRow {
  id: string;
  name: string;
  name_chinese: string | null;
  name_english: string | null;
  contact_person: string | null;
  phone: string | null;
  address: string | null;
  tax_id: string | null;
  payment_terms: string | null;
  default_currency: Currency;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface SalesOrderRow {
  id: string;
  so_number: string | null;
  customer_id: string;
  order_date: string;
  expected_delivery_date: string | null;
  currency: Currency;
  status: SoStatus;
  notes: string | null;
  attachment_path: string | null;
  created_by: string | null;
  confirmed_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface SalesOrderItemRow {
  id: string;
  sales_order_id: string;
  sku_id: string;
  location_id: string;
  unit: string;
  ordered_qty: number;
  unit_price: number;
  line_total: number;
  created_at: string;
}

export interface SalesOrderItemDeliveredRow {
  item_id: string;
  delivered_qty: number;
}

// --- Payroll (Fourth pass) -----------------------------------------------------

export interface PayrollRunRow {
  id: string;
  period_start: string;
  period_end: string;
  pay_date: string;
  status: PayrollStatus;
  notes: string | null;
  created_by: string | null;
  approved_by: string | null;
  approved_at: string | null;
  paid_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface PayrollItemRow {
  id: string;
  payroll_run_id: string;
  employee_id: string;
  pay_type: 'daily';
  days_worked: number | null;
  rate: number;
  base_amount: number;
  created_at: string;
}

export interface PayrollItemLineRow {
  id: string;
  payroll_item_id: string;
  kind: DeductionKind;
  label: string;
  amount: number;
  created_at: string;
}

export interface PayrollItemDeductionsRow {
  item_id: string;
  deductions_total: number;
}
