/**
 * Hand-maintained row types for the tables this app reads/writes.
 *
 * These mirror supabase/migrations. After connecting a real database you can
 * regenerate a fully-typed client with:
 *   supabase gen types typescript --local > src/lib/db/database.types.ts
 * and swap the untyped clients for `createClient<Database>()`. Until then these
 * interfaces are the type boundary for query results.
 */

import type { Role } from '@/lib/domain/rbac';
import type { ConditionCode } from '@/lib/domain/products';
import type { MovementType } from '@/lib/domain/stock-ledger';
import type { AttendanceStatus, Shift } from '@/lib/domain/attendance';
import type { Currency, PoStatus } from '@/lib/domain/purchasing';
import type { SoStatus } from '@/lib/domain/sales';
import type { PayrollStatus, DeductionKind } from '@/lib/domain/payroll';
import type { DepositInvoiceStatus, SoPaymentStatus } from '@/lib/domain/deposit-invoice';
import type { PaymentReceiptType } from '@/lib/domain/payment-receipt';

export interface ProfileRow {
  id: string;
  email: string;
  full_name: string | null;
  role: Role;
  is_active: boolean;
  created_at: string;
}

export interface LocationRow {
  id: string;
  code: string;
  name: string;
  is_active: boolean;
  created_at: string;
}

export interface ProductFamilyRow {
  id: string;
  code: string;
  name: string; // Chinese product-family name (required)
  name_english: string | null;
  default_unit: string;
  description: string | null;
  is_active: boolean;
  created_at: string;
}

export interface SkuRow {
  id: string;
  family_id: string;
  diameter: string | null;
  size: string | null;
  hole: string | null;
  rod_count: string | null;
  extra: string | null;
  condition: ConditionCode;
  unit: string;
  minimum_level: number;
  is_active: boolean;
  notes: string | null;
  created_at: string;
}

export interface StockMovementRow {
  id: string;
  sku_id: string;
  location_id: string;
  type: MovementType;
  quantity: number; // signed
  business_date: string; // YYYY-MM-DD
  transfer_group_id: string | null;
  override_reason: string | null;
  notes: string | null;
  attachment_path: string | null;
  purchase_order_item_id: string | null;
  batch_reference: string | null;
  created_by: string | null;
  created_at: string;
}

export interface AttendanceGroupRow {
  id: string;
  name: string;
  sort_order: number;
  is_active: boolean;
  created_at: string;
}

/** Non-sensitive employee columns (public.employees). */
export interface EmployeeRow {
  id: string;
  employee_code: string; // ZY-0001, generated by the DB
  seq_no: number; // permanent, never-reused sequence number
  name_khmer: string | null;
  name_english: string | null;
  name_chinese: string | null;
  phone: string | null;
  department: string | null;
  position: string | null;
  start_date: string | null;
  is_active: boolean;
  pay_type: 'daily';
  photo_path: string | null;
  photo_thumb_path: string | null;
  notes: string | null;
  // Attendance-group profile fields (used by the grouped report).
  attendance_group_id: string | null;
  display_name: string | null;
  job_title: string | null;
  label: string | null;
  created_at: string;
}

/**
 * Sensitive employee payroll data (public.employee_private). RLS restricts reads
 * to Owner / System Admin / Payroll Admin.
 */
export interface EmployeePrivateRow {
  employee_id: string;
  base_salary: number | null;
  daily_rate: number | null;
  emergency_contact: string | null;
  updated_at: string;
}

export interface AttendanceRow {
  id: string;
  employee_id: string;
  business_date: string;
  shift: Shift;
  status: Exclude<AttendanceStatus, 'unmarked'>;
  notes: string | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface AuditLogRow {
  id: string;
  actor_id: string | null;
  actor_email: string | null;
  action: string;
  entity: string;
  entity_id: string | null;
  old_value: unknown;
  new_value: unknown;
  created_at: string;
}

export interface LoginEventRow {
  id: string;
  user_id: string | null;
  email: string | null;
  ip_address: string | null;
  country: string | null;
  city: string | null;
  user_agent: string | null;
  created_at: string;
}

export interface SentReportRow {
  id: string;
  report_key: string; // idempotency key, e.g. attendance:morning:2026-07-24
  report_type: string;
  business_date: string;
  chat_id: string | null;
  destination_group: 'attendance' | 'inventory' | null;
  status: 'sent' | 'failed';
  detail: string | null;
  created_at: string;
}

export interface QuotationRow {
  id: string;
  customer_id: string | null;
  customer_name: string;
  contact: string | null;
  project_site: string | null;
  quotation_date: string;
  valid_days: number;
  currency: string;
  deposit_pct: number;
  pricing_basis: string | null;
  terms: string | null;
  notes: string | null;
  quotation_no: string | null;
  quotation_issued_on: string | null;
  deposit_no: string | null;
  deposit_issued_on: string | null;
  balance_no: string | null;
  balance_issued_on: string | null;
  deposit_paid_on: string | null;
  balance_paid_on: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface QuotationItemRow {
  id: string;
  quotation_id: string;
  line_no: number;
  description: string;
  wire_dia: string | null;
  steel_grade: string | null;
  unit: string;
  unit_price: number;
  quantity: number;
  total_sheets: number | null;
  amount: number; // generated
  created_at: string;
}

export interface OvertimeSettingsRow {
  id: number;
  tier1_label: string;
  tier1_rate: number;
  tier2_label: string;
  tier2_rate: number;
  currency: string;
  updated_at: string;
}

export interface OvertimeEntryRow {
  id: string;
  business_date: string;
  employee_id: string;
  description: string | null;
  time_range: string | null;
  tier1_hours: number;
  tier2_hours: number;
  tier1_rate: number;
  tier2_rate: number;
  // Generated columns (the 加班表 formula).
  tier1_amount: number;
  tier2_amount: number;
  total_amount: number;
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface InquiryCustomerTypeRow {
  id: string;
  name: string;
  sort_order: number;
  is_active: boolean;
  created_at: string;
}

export interface InquiryStatusRow {
  id: string;
  name: string;
  category: 'open' | 'won' | 'lost';
  sort_order: number;
  is_active: boolean;
  created_at: string;
}

export interface SalesInquiryRow {
  id: string;
  inquiry_no: string | null;
  inquiry_date: string;
  salesperson_id: string | null;
  customer_id: string | null;
  customer_name: string;
  company_name: string | null;
  contact: string | null;
  customer_type_id: string | null;
  family_id: string | null;
  specification: string | null;
  diameter: string | null;
  sheet_size: string | null;
  area_per_sheet: number | null;
  mesh_opening: string | null;
  quantity: number | null;
  delivery_location: string | null;
  factory_cost: number | null;
  quoted_price: number | null;
  target_price: number | null;
  final_price: number | null;
  status_id: string | null;
  follow_up_date: string | null;
  follow_up_notes: string | null;
  next_action: string | null;
  remarks: string | null;
  // Generated (derived) columns.
  price_difference: number | null;
  quotation_value: number | null;
  estimated_profit: number | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface InquiryFollowupRow {
  id: string;
  inquiry_id: string;
  follow_up_date: string;
  previous_action: string | null;
  customer_response: string | null;
  next_follow_up_date: string | null;
  responsible_id: string | null;
  status_id: string | null;
  created_by: string | null;
  created_at: string;
}

export interface TelegramSettingsRow {
  id: number;
  morning_enabled: boolean;
  afternoon_enabled: boolean;
  inventory_enabled: boolean;
  morning_time: string; // HH:mm (Asia/Bangkok) — attendance morning
  afternoon_time: string; // HH:mm (Asia/Bangkok) — attendance afternoon
  inventory_time: string; // HH:mm (Asia/Bangkok) — daily inventory
  report_language: 'en' | 'zh'; // future-ready; reports currently always Chinese
  // --- Attendance Group destination (morning + afternoon reports) -----------
  attendance_chat_id: string | null;
  attendance_group_enabled: boolean;
  attendance_last_status: 'sent' | 'failed' | null;
  attendance_last_error: string | null;
  attendance_last_sent_at: string | null;
  // --- Inventory Group destination (daily inventory report) -----------------
  inventory_chat_id: string | null;
  inventory_group_enabled: boolean;
  inventory_last_status: 'sent' | 'failed' | null;
  inventory_last_error: string | null;
  inventory_last_sent_at: string | null;
  updated_at: string;
}

// --- Purchasing (Second pass) ------------------------------------------------

export interface SupplierRow {
  id: string;
  name: string;
  name_chinese: string | null;
  name_english: string | null;
  contact_person: string | null;
  phone: string | null;
  address: string | null;
  tax_id: string | null;
  payment_terms: string | null;
  default_currency: Currency;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

// Note: the underlying table still has an `expected_arrival_date` column
// (nullable, never dropped — historical values are preserved), but the app
// no longer reads or writes it: the Overdue/Expected Arrival feature was
// removed. Omitted here deliberately since nothing in the app uses it.
export interface PurchaseOrderRow {
  id: string;
  po_number: string | null;
  supplier_id: string;
  order_date: string;
  currency: Currency;
  status: PoStatus;
  notes: string | null;
  attachment_path: string | null;
  created_by: string | null;
  issued_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}

/** Free-text product line on a PO — no sku_id, no catalog connection. */
export interface PurchaseOrderManualItemRow {
  id: string;
  purchase_order_id: string;
  product_name: string;
  quantity: number | null;
  unit: string | null;
  unit_price: number | null;
  line_total: number | null;
  created_at: string;
}

// --- Sales (Third pass) -------------------------------------------------------

export interface CustomerRow {
  id: string;
  customer_code: string;
  name: string;
  name_chinese: string | null;
  name_english: string | null;
  contact_person: string | null;
  phone: string | null;
  address: string | null;
  tax_id: string | null;
  payment_terms: string | null;
  default_currency: Currency;
  notes: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface SalesOrderRow {
  id: string;
  so_number: string | null;
  customer_id: string;
  order_date: string;
  expected_delivery_date: string | null;
  currency: Currency;
  status: SoStatus;
  payment_status: SoPaymentStatus;
  notes: string | null;
  attachment_path: string | null;
  /** Set when this order was auto-created from a Quotation's paid deposit — see markPaid. */
  quotation_id: string | null;
  /** Simple paid flags — mirrors quotations.deposit_paid_on/balance_paid_on, not an amount ledger. */
  deposit_paid_on: string | null;
  balance_paid_on: string | null;
  created_by: string | null;
  confirmed_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface SalesOrderItemRow {
  id: string;
  sales_order_id: string;
  sku_id: string;
  location_id: string;
  unit: string;
  ordered_qty: number;
  unit_price: number;
  line_total: number;
  area_per_sheet: number | null;
  price_per_sqm: number | null;
  created_at: string;
}

export interface SalesOrderItemDeliveredRow {
  item_id: string;
  delivered_qty: number;
}

export interface DepositInvoiceRow {
  id: string;
  invoice_number: string | null;
  sales_order_id: string;
  deposit_percentage: number;
  total_order_amount: number;
  deposit_amount: number;
  remaining_balance: number;
  currency: Currency;
  status: DepositInvoiceStatus;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface DepositInvoicePaymentRow {
  id: string;
  deposit_invoice_id: string;
  amount: number;
  paid_date: string;
  method: string | null;
  notes: string | null;
  recorded_by: string | null;
  created_at: string;
}

export interface PaymentReceiptRow {
  id: string;
  receipt_number: string | null;
  sales_order_id: string;
  deposit_invoice_id: string;
  receipt_type: PaymentReceiptType;
  amount: number;
  paid_date: string;
  method: string | null;
  notes: string | null;
  recorded_by: string | null;
  created_at: string;
}

// --- Payroll (Fourth pass) -----------------------------------------------------

export interface PayrollRunRow {
  id: string;
  period_start: string;
  period_end: string;
  pay_date: string;
  status: PayrollStatus;
  notes: string | null;
  created_by: string | null;
  approved_by: string | null;
  approved_at: string | null;
  paid_at: string | null;
  cancelled_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface PayrollItemRow {
  id: string;
  payroll_run_id: string;
  employee_id: string;
  pay_type: 'daily';
  days_worked: number | null;
  rate: number;
  base_amount: number;
  created_at: string;
}

export interface PayrollItemLineRow {
  id: string;
  payroll_item_id: string;
  kind: DeductionKind;
  label: string;
  amount: number;
  created_at: string;
}

export interface PayrollItemDeductionsRow {
  item_id: string;
  deductions_total: number;
}

/** Recomputed-from-current-attendance figures for a Draft run's item (public.payroll_items_live). */
export interface PayrollItemLiveRow {
  id: string;
  payroll_run_id: string;
  employee_id: string;
  live_days_worked: number;
  live_rate: number;
  live_base_amount: number;
  live_overtime_amount: number;
}

// --- Sales & Marketing Toolkit: sales targets (sheet 18), KPI (sheet 07) -------

export interface SalesTargetRow {
  id: string;
  employee_id: string;
  period: string; // YYYY-MM
  revenue_target: number;
  target_margin_pct: number;
  gp_target: number; // generated: revenue_target * target_margin_pct
  orders_target: number;
  new_customers: number;
  quotations_week: number;
  qualified_week: number;
  contacts_day: number;
  visits_day: number;
  leads_day: number;
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface KpiScorecardRow {
  id: string;
  employee_id: string;
  period: string; // YYYY-MM
  notes: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface KpiScorecardLineRow {
  id: string;
  scorecard_id: string;
  line_no: number;
  label: string;
  weight: number;
  target_value: number | null;
  actual_value: number | null;
  lower_is_better: boolean;
  created_at: string;
}
