'use server';
import { revalidatePath } from 'next/cache';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { assertPermission } from '@/lib/auth';
import { writeAudit } from '@/lib/audit';
import { businessDate } from '@/lib/domain/datetime';
import { DOC_PREFIX, normalizeDepositPct, type DocumentKind } from '@/lib/domain/quotation';
import {
  quotationSchema,
  quotationUpdateSchema,
  issueDocumentSchema,
  updateQuotationDepositPctSchema,
  type QuotationItemInput,
} from '@/lib/validation/schemas';
import { fail, ok, zodFieldErrors, type ActionState } from './types';

const LIST_PATH = '/sales/quotations';

/** Parse the repeated line-item fields the editor submits. */
function parseItems(formData: FormData): unknown[] {
  const descriptions = formData.getAll('itemDescription');
  return descriptions.map((_, i) => ({
    description: formData.getAll('itemDescription')[i],
    wireDia: formData.getAll('itemWireDia')[i],
    steelGrade: formData.getAll('itemSteelGrade')[i],
    unit: formData.getAll('itemUnit')[i],
    unitPrice: formData.getAll('itemUnitPrice')[i],
    quantity: formData.getAll('itemQuantity')[i],
  }));
}

function quotationForm(formData: FormData) {
  return {
    customerId: formData.get('customerId'),
    customerName: formData.get('customerName'),
    contact: formData.get('contact'),
    projectSite: formData.get('projectSite'),
    quotationDate: formData.get('quotationDate') || businessDate(),
    validDays: formData.get('validDays') || 15,
    currency: formData.get('currency') || 'USD',
    depositPct: formData.get('depositPct') || 30,
    pricingBasis: formData.get('pricingBasis'),
    notes: formData.get('notes'),
    items: parseItems(formData).filter(
      (i) => String((i as { description?: unknown }).description ?? '').trim().length > 0,
    ),
  };
}

function itemRows(quotationId: string, items: QuotationItemInput[]) {
  return items.map((it, idx) => ({
    quotation_id: quotationId,
    line_no: idx + 1,
    description: it.description,
    wire_dia: it.wireDia ?? null,
    steel_grade: it.steelGrade ?? null,
    unit: it.unit,
    unit_price: it.unitPrice,
    quantity: it.quantity,
  }));
}

export async function createQuotation(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const user = await assertPermission('sales:manage');
  const parsed = quotationSchema.safeParse(quotationForm(formData));
  if (!parsed.success)
    return fail('Please check the highlighted fields', zodFieldErrors(parsed.error.issues));
  const d = parsed.data;

  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase
    .from('quotations')
    .insert({
      customer_id: d.customerId ?? null,
      customer_name: d.customerName,
      contact: d.contact ?? null,
      project_site: d.projectSite ?? null,
      quotation_date: d.quotationDate,
      valid_days: d.validDays,
      currency: d.currency,
      deposit_pct: normalizeDepositPct(d.depositPct),
      pricing_basis: d.pricingBasis ?? null,
      notes: d.notes ?? null,
      created_by: user.id,
    })
    .select('id')
    .single();
  if (error) return fail(error.message);

  const { error: itemsError } = await supabase
    .from('quotation_items')
    .insert(itemRows(data.id, d.items));
  if (itemsError) return fail(itemsError.message);

  await writeAudit(user, {
    action: 'quotation.create',
    entity: 'quotations',
    entityId: data.id,
    newValue: { customer: d.customerName, lines: d.items.length },
  });
  revalidatePath(LIST_PATH);
  return ok('Quotation created', { quotationId: data.id });
}

export async function updateQuotation(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const user = await assertPermission('sales:manage');
  const parsed = quotationUpdateSchema.safeParse({
    id: formData.get('id'),
    ...quotationForm(formData),
  });
  if (!parsed.success)
    return fail('Please check the highlighted fields', zodFieldErrors(parsed.error.issues));
  const { id, items, ...d } = parsed.data;

  const supabase = await createSupabaseServerClient();
  const { error } = await supabase
    .from('quotations')
    .update({
      customer_id: d.customerId ?? null,
      customer_name: d.customerName,
      contact: d.contact ?? null,
      project_site: d.projectSite ?? null,
      quotation_date: d.quotationDate,
      valid_days: d.validDays,
      currency: d.currency,
      deposit_pct: normalizeDepositPct(d.depositPct),
      pricing_basis: d.pricingBasis ?? null,
      notes: d.notes ?? null,
    })
    .eq('id', id);
  if (error) return fail(error.message);

  // Line items are replaced wholesale — simplest correct behaviour, and the
  // amounts are regenerated by the database either way.
  await supabase.from('quotation_items').delete().eq('quotation_id', id);
  const { error: itemsError } = await supabase.from('quotation_items').insert(itemRows(id, items));
  if (itemsError) return fail(itemsError.message);

  await writeAudit(user, {
    action: 'quotation.update',
    entity: 'quotations',
    entityId: id,
    newValue: { customer: d.customerName, lines: items.length },
  });
  revalidatePath(LIST_PATH);
  revalidatePath(`${LIST_PATH}/${id}`);
  return ok('Quotation updated');
}

/** Quick inline edit — just the deposit share, from the list row, no line items touched. */
export async function updateQuotationDepositPct(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const user = await assertPermission('sales:manage');
  const parsed = updateQuotationDepositPctSchema.safeParse({
    id: formData.get('id'),
    depositPct: formData.get('depositPct'),
  });
  if (!parsed.success)
    return fail('Please check the highlighted fields', zodFieldErrors(parsed.error.issues));
  const { id, depositPct } = parsed.data;

  const supabase = await createSupabaseServerClient();
  const { error } = await supabase
    .from('quotations')
    .update({ deposit_pct: normalizeDepositPct(depositPct) })
    .eq('id', id);
  if (error) return fail(error.message);

  await writeAudit(user, {
    action: 'quotation.update_deposit_pct',
    entity: 'quotations',
    entityId: id,
    newValue: { depositPct },
  });
  revalidatePath(LIST_PATH);
  return ok('Deposit percentage updated');
}

export async function deleteQuotation(
  _prev: ActionState,
  formData: FormData,
): Promise<ActionState> {
  const user = await assertPermission('sales:manage');
  const id = String(formData.get('id') ?? '');
  if (!id) return fail('Missing quotation');

  const supabase = await createSupabaseServerClient();
  const { error } = await supabase.from('quotations').delete().eq('id', id);
  if (error) return fail(error.message);

  await writeAudit(user, { action: 'quotation.delete', entity: 'quotations', entityId: id });
  revalidatePath(LIST_PATH);
  return ok('Quotation deleted');
}

/**
 * Assign the document number for one of the three documents (idempotent — the
 * RPC returns the existing number if it was already issued, so regenerating a
 * PDF never burns a new sequence number).
 */
export async function issueDocument(_prev: ActionState, formData: FormData): Promise<ActionState> {
  const user = await assertPermission('sales:manage');
  const parsed = issueDocumentSchema.safeParse({
    quotationId: formData.get('quotationId'),
    kind: formData.get('kind'),
  });
  if (!parsed.success) return fail('Invalid document request');
  const { quotationId, kind } = parsed.data;

  const supabase = await createSupabaseServerClient();
  const { data, error } = await supabase.rpc('issue_quotation_document', {
    p_quotation: quotationId,
    p_kind: DOC_PREFIX[kind as DocumentKind],
    p_issue_date: businessDate(),
  });
  if (error) return fail(error.message);

  await writeAudit(user, {
    action: `quotation.issue_${kind}`,
    entity: 'quotations',
    entityId: quotationId,
    newValue: { docNo: data },
  });
  revalidatePath(`${LIST_PATH}/${quotationId}`);
  return ok('Document issued', { docNo: data as string });
}

/** Record that the deposit or the balance has been paid. */
export async function markPaid(_prev: ActionState, formData: FormData): Promise<ActionState> {
  const user = await assertPermission('sales:manage');
  const id = String(formData.get('id') ?? '');
  const which = String(formData.get('which') ?? '');
  if (!id || (which !== 'deposit' && which !== 'balance')) return fail('Invalid payment request');

  const column = which === 'deposit' ? 'deposit_paid_on' : 'balance_paid_on';
  const supabase = await createSupabaseServerClient();
  const { error } = await supabase
    .from('quotations')
    .update({ [column]: businessDate() })
    .eq('id', id);
  if (error) return fail(error.message);

  await writeAudit(user, {
    action: `quotation.${which}_paid`,
    entity: 'quotations',
    entityId: id,
  });
  revalidatePath(`${LIST_PATH}/${id}`);
  return ok(which === 'deposit' ? 'Deposit marked paid' : 'Balance marked paid');
}
