'use client';
import { useActionState, useEffect, useRef, useState } from 'react';
import { Loader2, Upload, User, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useT } from '@/components/i18n-provider';
import { createSupabaseBrowserClient } from '@/lib/supabase/client';
import { createEmployee, setEmployeePhoto } from '@/lib/actions/employees';
import type { ActionState } from '@/lib/actions/types';
import type { AttendanceGroupRow } from '@/lib/db/types';

const selectCls =
  'flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';

const BLANK = {
  displayName: '',
  attendanceGroupId: '',
  jobTitle: '',
  employeeNumber: '',
  label: '',
  nameChinese: '',
  phone: '',
  department: '',
  startDate: '',
  payType: 'monthly',
  notes: '',
};

type PhotoStatus = null | 'uploading' | 'done' | 'failed';

export function CreateEmployeeForm({ groups }: { groups: AttendanceGroupRow[] }) {
  const { t, m } = useT();
  const [state, formAction, pending] = useActionState<ActionState, FormData>(createEmployee, null);
  const [v, setV] = useState({ ...BLANK });

  // Optional photo — staged locally and uploaded AFTER the employee is created.
  const [photoFile, setPhotoFile] = useState<File | null>(null);
  const [photoPreview, setPhotoPreview] = useState<string | null>(null);
  const [photoStatus, setPhotoStatus] = useState<PhotoStatus>(null);
  const uploadedFor = useRef<string | null>(null);

  function pickPhoto(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0] ?? null;
    setPhotoFile(file);
    setPhotoPreview((prev) => {
      if (prev) URL.revokeObjectURL(prev);
      return file ? URL.createObjectURL(file) : null;
    });
  }
  function clearPhoto() {
    setPhotoFile(null);
    setPhotoPreview((prev) => {
      if (prev) URL.revokeObjectURL(prev);
      return null;
    });
  }

  // On success: upload the staged photo (non-blocking), then clear the form.
  useEffect(() => {
    if (!state?.ok) return;
    const employeeId = state.data?.employeeId as string | undefined;
    if (employeeId && photoFile && uploadedFor.current !== employeeId) {
      uploadedFor.current = employeeId;
      const file = photoFile;
      setPhotoStatus('uploading');
      void (async () => {
        try {
          const supabase = createSupabaseBrowserClient();
          const ext = file.name.split('.').pop() || 'jpg';
          const path = `${employeeId}/${Date.now()}.${ext}`;
          const { error } = await supabase.storage
            .from('employee-photos')
            .upload(path, file, { upsert: true, contentType: file.type });
          if (error) {
            setPhotoStatus('failed');
            return;
          }
          const fd = new FormData();
          fd.set('employeeId', employeeId);
          fd.set('path', path);
          const res = await setEmployeePhoto(null, fd);
          setPhotoStatus(res && !res.ok ? 'failed' : 'done');
        } catch {
          setPhotoStatus('failed');
        }
      })();
    }
    setV({ ...BLANK });
    clearPhoto();
  }, [state]); // eslint-disable-line react-hooks/exhaustive-deps

  const set =
    (k: keyof typeof BLANK) => (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) =>
      setV((s) => ({ ...s, [k]: e.target.value }));
  const fieldError = (k: string) => {
    const msg = state?.fieldErrors?.[k];
    return msg ? <p className="text-xs text-destructive">{m(msg)}</p> : null;
  };
  const invalid = (k: string) => (state?.fieldErrors?.[k] ? 'border-destructive' : '');

  return (
    <form action={formAction} className="space-y-4">
      {/* Employee ID is generated by the database — shown read-only. */}
      <div className="flex items-center gap-2 rounded-md bg-muted px-3 py-2 text-sm">
        <span className="text-muted-foreground">{t('emp.employeeId')}:</span>
        <span className="font-mono font-medium">{t('emp.employeeIdAuto')}</span>
      </div>

      {/* Photo (optional) — uploaded right after the employee is created. */}
      <div className="flex items-center gap-3">
        <div className="flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-full bg-muted">
          {photoPreview ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={photoPreview} alt="" className="h-full w-full object-cover" />
          ) : (
            <User className="h-6 w-6 text-muted-foreground" />
          )}
        </div>
        <div className="space-y-1">
          <Label>{t('emp.photoOptional')}</Label>
          <div className="flex items-center gap-2">
            <Button asChild variant="outline" size="sm">
              <label className="cursor-pointer">
                <Upload className="h-4 w-4" /> {t('emp.choosePhoto')}
                <input type="file" accept="image/*" className="hidden" onChange={pickPhoto} />
              </label>
            </Button>
            {photoFile && (
              <Button variant="ghost" size="sm" type="button" onClick={clearPhoto}>
                <X className="h-4 w-4" /> {t('emp.removePhoto')}
              </Button>
            )}
          </div>
          <p className="text-xs text-muted-foreground">{t('emp.photoHint')}</p>
        </div>
      </div>

      {/* Required */}
      <div className="grid gap-3 sm:grid-cols-3">
        <div className="space-y-1.5">
          <Label htmlFor="ce-display">
            {t('emp.english')} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="ce-display"
            name="displayName"
            value={v.displayName}
            onChange={set('displayName')}
            className={invalid('displayName')}
            placeholder="Sok Dara"
          />
          {fieldError('displayName')}
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="ce-group">
            {t('emp.group')} <span className="text-destructive">*</span>
          </Label>
          <select
            id="ce-group"
            name="attendanceGroupId"
            value={v.attendanceGroupId}
            onChange={set('attendanceGroupId')}
            className={`${selectCls} ${invalid('attendanceGroupId')}`}
          >
            <option value="">{t('common.select')}</option>
            {groups.map((g) => (
              <option key={g.id} value={g.id}>
                {g.name}
              </option>
            ))}
          </select>
          {fieldError('attendanceGroupId')}
        </div>
        <div className="space-y-1.5">
          <Label htmlFor="ce-title">
            {t('emp.jobTitle')} <span className="text-destructive">*</span>
          </Label>
          <Input
            id="ce-title"
            name="jobTitle"
            value={v.jobTitle}
            onChange={set('jobTitle')}
            className={invalid('jobTitle')}
          />
          {fieldError('jobTitle')}
        </div>
      </div>

      {/* Optional */}
      <div>
        <div className="mb-1 text-xs font-medium uppercase tracking-wide text-muted-foreground">
          {t('emp.optionalDetails')}
        </div>
        <p className="mb-2 text-xs text-muted-foreground">{t('emp.optionalNote')}</p>
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <div className="space-y-1.5">
            <Label htmlFor="ce-number">{t('emp.numberHint')}</Label>
            <Input
              id="ce-number"
              name="employeeNumber"
              value={v.employeeNumber}
              onChange={set('employeeNumber')}
              placeholder="7"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="ce-label">{t('emp.labelHint')}</Label>
            <Input
              id="ce-label"
              name="label"
              value={v.label}
              onChange={set('label')}
              placeholder="备用"
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="ce-pay">{t('emp.payType')}</Label>
            <select
              id="ce-pay"
              name="payType"
              value={v.payType}
              onChange={set('payType')}
              className={selectCls}
            >
              <option value="monthly">{t('emp.monthly')}</option>
              <option value="daily">{t('emp.daily')}</option>
            </select>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="ce-zh">{t('emp.chinese')}</Label>
            <Input
              id="ce-zh"
              name="nameChinese"
              value={v.nameChinese}
              onChange={set('nameChinese')}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="ce-phone">{t('emp.phone')}</Label>
            <Input id="ce-phone" name="phone" value={v.phone} onChange={set('phone')} />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="ce-dept">{t('emp.department')}</Label>
            <Input
              id="ce-dept"
              name="department"
              value={v.department}
              onChange={set('department')}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="ce-start">{t('emp.startDate')}</Label>
            <Input
              id="ce-start"
              name="startDate"
              type="date"
              value={v.startDate}
              onChange={set('startDate')}
            />
          </div>
        </div>
      </div>

      {state?.error && (
        <p className="rounded-md bg-destructive/10 px-3 py-1.5 text-sm text-destructive">
          {m(state.error)}
        </p>
      )}
      {state?.ok && state.message && (
        <p className="rounded-md bg-success/10 px-3 py-1.5 text-sm text-success">
          {m(state.message)}
        </p>
      )}
      {photoStatus === 'uploading' && (
        <p className="text-xs text-muted-foreground">{t('emp.photoUploading')}</p>
      )}
      {photoStatus === 'done' && <p className="text-xs text-success">{t('emp.photoUploaded')}</p>}
      {photoStatus === 'failed' && <p className="text-xs text-warning">{t('emp.photoFailed')}</p>}

      <Button type="submit" disabled={pending}>
        {pending && <Loader2 className="h-4 w-4 animate-spin" />}
        {t('emp.create')}
      </Button>
    </form>
  );
}
